[package]
name = "halt"
version = "0.1.0"
authors = ["August Lilleaas <august@augustl.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.4"


[package.metadata.bootimage]
default-target = "x86_64-os.json"