[package]
name = "halt"
version = "0.1.0"
authors = ["August Lilleaas <august@augustl.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.4"
x86_64 = "0.3.4"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[package.metadata.bootimage]
default-target = "x86_64-os.json"