#!/bin/sh

. script/_env.sh

ensure_mount

BOOTLOADER_DIR="EFI/BOOT"

cd uefi_bootloader
make
cd ..
mkdir -p target/mnt/$BOOTLOADER_DIR
cp uefi_bootloader/uefi_bootloader.efi target/mnt/$BOOTLOADER_DIR/BOOTx64.EFI
