#!/bin/sh

OVMF_MIRROR=http://heanet.dl.sourceforge.net/project/edk2/OVMF/OVMF-X64-r15214.zip

mkdir -p target/qemu_bios
curl -o target/OVMF.zip -LO $OVMF_MIRROR
cd target
mkdir ovmf
mv OVMF.zip ovmf/
cd ovmf
unzip -x OVMF.zip
mv OVMF.fd ../qemu_bios/bios.bin
cd ..
rm -rf ovmf
